[package]
name = "mwc-web3"
version = "0.20.1"
description = "Ethereum JSON-RPC client."
homepage = "https://github.com/tomusdrw/rust-web3"
repository = "https://github.com/tomusdrw/rust-web3"
documentation = "https://docs.rs/web3"
license = "MIT"
keywords = ["jsonrpc", "web3", "ethereum", "rpc", "client"]
authors = ["Tomasz Drwięga <tomasz@parity.io>"]
readme = "README.md"
edition = "2024"
rust-version = "1.88"

[dependencies]
derive_more = { version = "2.1", features = ["display", "from"] }
ethabi = "18.0.0"
ethereum-types = "0.16"
futures = "0.3"
futures-timer = "3.0"
hex = "0.4"
idna = "1.1"
jsonrpc-core = "18.0"
log = "0.4"
parking_lot = "0.12"
rlp = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny-keccak = { version = "2.0", features = ["keccak"] }
pin-project = "1.1"
# Optional deps
secp256k1 = { version = "0.31", features = ["recovery"], optional = true }
once_cell = { version = "1.21", optional = true }

## HTTP
base64 = { version = "0.22", optional = true }
bytes = { version = "1", optional = true }
reqwest = { version = "0.13", optional = true, default-features = false, features = ["json", "stream"] }
headers = { version = "0.4", optional = true }
## WS
async-native-tls = { version = "0.6", optional = true, default-features = false }
native-tls = { version = "0.2", optional = true }
tokio-native-tls = { version = "0.3", optional = true }
tokio-rustls = { version = "0.26", optional = true }
rustls-pki-types = { version = "1", optional = true }
webpki-roots = { version = "1", optional = true }
async-global-executor = { version = "3.1", optional = true }
async-net = { version = "2", optional = true }
tokio = { version = "1.52", optional = true, features = ["full"] }
tokio-stream = { version = "0.1", optional = true }
tokio-util = { version = "0.7", optional = true, features = ["compat", "io"] }
soketto = { version = "0.8", optional = true }
## Shared (WS, HTTP)
url = { version = "2.5", optional = true }
## EIP-1193
js-sys = { version = "0.3", optional = true }
### This is a transitive dependency, only here so we can turn on its wasm_bindgen feature
getrandom = { version = "0.4", features = ["wasm_js"], optional = true }
rand = { version = "0.10", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }

[dev-dependencies]
# For examples
env_logger = "0.11"
hex-literal = "1.1"
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
hyper = { version = "1.4", default-features = false, features = ["server"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }

[features]
default = ["http-tls", "signing", "ws-tls-tokio", "ipc-tokio"]
wasm = ["futures-timer/wasm-bindgen", "getrandom", "js-sys", "rand", "serde-wasm-bindgen", "wasm-bindgen", "wasm-bindgen-futures"]
eip-1193 = ["wasm"]
_http_base = ["reqwest", "bytes", "url", "base64"]
http = ["_http_base"]
http-tls = ["http", "reqwest/default-tls"]
http-native-tls = ["http", "reqwest/native-tls"]
http-rustls-tls = ["http", "reqwest/rustls"]
signing = ["secp256k1", "once_cell"]
ws-tokio = ["soketto", "url", "tokio", "tokio-util", "headers"]
ws-async-io = ["soketto", "url", "async-global-executor", "async-net", "headers"]
ws-async-std = ["ws-async-io"]
ws-tls-tokio = ["native-tls", "tokio-native-tls", "ws-tokio"]
ws-rustls-tokio = ["tokio-rustls", "webpki-roots", "rustls-pki-types", "ws-tokio"]
ws-tls-async-io = ["async-native-tls", "async-native-tls/runtime-smol", "ws-async-io"]
ws-tls-async-std = ["ws-tls-async-io"]
ipc-tokio = ["tokio", "tokio-stream", "tokio-util"]
arbitrary_precision = ["serde_json/arbitrary_precision", "jsonrpc-core/arbitrary_precision"]
test = []
allow-missing-fields = []

[workspace]
